package com.myspace.insurancepolicyrulestoringresponse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Insurance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double annual_income;
	private int age;
	private double premium_amount;
	private java.lang.String statusAnnualIncome;

	private java.lang.String statusAge;

	private java.lang.String statusOccupation;

	private java.lang.String statusPremiumAmount;

	private java.lang.String statusMedical_History;

	private java.lang.String statusFinal;

	private int ageinput;

	private java.lang.String medicleinput;

	private java.lang.String occupationinput;

	private double annualinputinput;

	private double premiumamountinput;

	private java.util.List<java.lang.String> occupation;

	private java.util.List<java.lang.String> medical_history;

	private boolean mediB;

	private boolean occupB;

	private boolean countryB;

	private java.lang.String pincode;

	private java.lang.String statusPincode;

	public Insurance() {
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.String getStatusAnnualIncome() {
		return this.statusAnnualIncome;
	}

	public void setStatusAnnualIncome(java.lang.String statusAnnualIncome) {
		this.statusAnnualIncome = statusAnnualIncome;
	}

	public java.lang.String getStatusAge() {
		return this.statusAge;
	}

	public void setStatusAge(java.lang.String statusAge) {
		this.statusAge = statusAge;
	}

	public java.lang.String getStatusOccupation() {
		return this.statusOccupation;
	}

	public void setStatusOccupation(java.lang.String statusOccupation) {
		this.statusOccupation = statusOccupation;
	}

	public java.lang.String getStatusPremiumAmount() {
		return this.statusPremiumAmount;
	}

	public void setStatusPremiumAmount(java.lang.String statusPremiumAmount) {
		this.statusPremiumAmount = statusPremiumAmount;
	}

	public java.lang.String getStatusMedical_History() {
		return this.statusMedical_History;
	}

	public void setStatusMedical_History(java.lang.String statusMedical_History) {
		this.statusMedical_History = statusMedical_History;
	}

	public double getAnnual_income() {
		return this.annual_income;
	}

	public void setAnnual_income(double annual_income) {
		this.annual_income = annual_income;
	}

	public double getPremium_amount() {
		return this.premium_amount;
	}

	public void setPremium_amount(double premium_amount) {
		this.premium_amount = premium_amount;
	}

	public java.lang.String getStatusFinal() {
		return this.statusFinal;
	}

	public void setStatusFinal(java.lang.String statusFinal) {
		this.statusFinal = statusFinal;
	}

	public int getAgeinput() {
		return this.ageinput;
	}

	public void setAgeinput(int ageinput) {
		this.ageinput = ageinput;
	}

	public java.lang.String getMedicleinput() {
		return this.medicleinput;
	}

	public void setMedicleinput(java.lang.String medicleinput) {
		this.medicleinput = medicleinput;
	}

	public java.lang.String getOccupationinput() {
		return this.occupationinput;
	}

	public void setOccupationinput(java.lang.String occupationinput) {
		this.occupationinput = occupationinput;
	}

	public double getAnnualinputinput() {
		return this.annualinputinput;
	}

	public void setAnnualinputinput(double annualinputinput) {
		this.annualinputinput = annualinputinput;
	}

	public double getPremiumamountinput() {
		return this.premiumamountinput;
	}

	public void setPremiumamountinput(double premiumamountinput) {
		this.premiumamountinput = premiumamountinput;
	}

	public java.util.List<java.lang.String> getOccupation() {
		return this.occupation;
	}

	public void setOccupation(java.util.List<java.lang.String> occupation) {
		this.occupation = occupation;
	}

	public java.util.List<java.lang.String> getMedical_history() {
		return this.medical_history;
	}

	public void setMedical_history(
			java.util.List<java.lang.String> medical_history) {
		this.medical_history = medical_history;
	}

	public boolean isMediB() {
		return this.mediB;
	}

	public void setMediB(boolean mediB) {
		this.mediB = mediB;
	}

	public boolean isOccupB() {
		return this.occupB;
	}

	public void setOccupB(boolean occupB) {
		this.occupB = occupB;
	}

	public boolean isCountryB() {
		return this.countryB;
	}

	public void setCountryB(boolean countryB) {
		this.countryB = countryB;
	}

	public java.lang.String getPincode() {
		return this.pincode;
	}

	public void setPincode(java.lang.String pincode) {
		this.pincode = pincode;
	}

	public java.lang.String getStatusPincode() {
		return this.statusPincode;
	}

	public void setStatusPincode(java.lang.String statusPincode) {
		this.statusPincode = statusPincode;
	}

	public Insurance(double annual_income, int age, double premium_amount,
			java.lang.String statusAnnualIncome, java.lang.String statusAge,
			java.lang.String statusOccupation,
			java.lang.String statusPremiumAmount,
			java.lang.String statusMedical_History,
			java.lang.String statusFinal, int ageinput,
			java.lang.String medicleinput, java.lang.String occupationinput,
			double annualinputinput, double premiumamountinput,
			java.util.List<java.lang.String> occupation,
			java.util.List<java.lang.String> medical_history, boolean mediB,
			boolean occupB, boolean countryB, java.lang.String pincode,
			java.lang.String statusPincode) {
		this.annual_income = annual_income;
		this.age = age;
		this.premium_amount = premium_amount;
		this.statusAnnualIncome = statusAnnualIncome;
		this.statusAge = statusAge;
		this.statusOccupation = statusOccupation;
		this.statusPremiumAmount = statusPremiumAmount;
		this.statusMedical_History = statusMedical_History;
		this.statusFinal = statusFinal;
		this.ageinput = ageinput;
		this.medicleinput = medicleinput;
		this.occupationinput = occupationinput;
		this.annualinputinput = annualinputinput;
		this.premiumamountinput = premiumamountinput;
		this.occupation = occupation;
		this.medical_history = medical_history;
		this.mediB = mediB;
		this.occupB = occupB;
		this.countryB = countryB;
		this.pincode = pincode;
		this.statusPincode = statusPincode;
	}

}